# Generated by Django 5.0.1 on 2024-02-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('code',), name='unique appversion'),
        ),
    ]
