# Generated by Django 5.0.1 on 2024-02-20 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_question_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='group',
            new_name='subjects',
        ),
    ]
